apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-aks-test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kafka-aks-test
    spec:
      containers:
        - name: kafka-aks-test
          image: microsoft/kafka-aks-test:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-aks-test
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: kafka-aks-test